development:
  adapter: postgresql
  database: worshiptuner_dev
  username: username
  password: password
  host: localhost
  port: 5432
  encoding: unicode
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: worshiptuner_test
  username: username
  password: password
  host: localhost
  port: 5432
  encoding: unicode
  pool: 5
  timeout: 5000